#!/usr/bin/env bash
# Configures my nginx server and add a custom header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html/index.html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default
sudo chown -R "$USER":"$USER" /var/www/html

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
    add_header X-Served-By \$hostname; 
	location /redirect_me {
		return 301 https://google.com;
	}
 	error_page 404 /custom_404.html;
    	location = /custom_404.html {
      		root /var/www/html;
      		internal;
    	}
}"

echo -e "$config" > /etc/nginx/sites-enabled/default

sudo service nginx restart
