#!/usr/bin/env bash
# Install and configure HAProxy
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install haproxy=2.6.\* -y
sudo apt update && sudo apt upgrade -y

sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

conf=\
"
global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon
defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
backend myservers
        balance roundrobin
        server 42996-web-01 3.237.5.158:80 check
        server 42996-web-02 54.172.252.98:80 check
frontend myfrontend
        bind :80
        mode http
        default_backend myservers
"

echo "$conf" > /etc/haproxy/haproxy.cfg

sudo service haproxy restart
