#!/usr/bin/env bash
# Install and configure HAProxy
sudo apt-get update
sudo apt-get upgrade -y
sudo apt install haproxy -y
sudo echo "ENABLED-=1" >> /etc/default/haproxy
sudo echo "frontend frontend
        bind *:80
        default_backend myservers
backend myservers
        balance roundrobin
        server 42996-web-01 3.237.5.158:80 check
        server 42996-web-02 54.172.252.98:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
